diagnostics1: 
  - id: 0x01
    fields:
      - name: "AkkuStatusRegister"
        offset: 0
        len: 2
        is_signed: false

      - name: "AkkuStatusRegister_2"
        offset: 2
        len: 2
        is_signed: false

      - name: "ProjectStatusRegister"
        offset: 4
        len: 2
        is_signed: false

      - name: "SystemStatusRegister"
        offset: 6
        len: 2
        is_signed: false

  - id: 0x02
    fields:
      - name: "AkkuCurrent"
        offset: 0
        len: 2
        is_signed: true
        factor: 0.01
        unit: "A"

  - id: 0x03
    fields:
      - name: "AkkuPackVoltage"
        offset: 0
        len: 2
        is_signed: false
        factor: 0.01
        unit: "V"

  - id: 0x06
    fields:
      - name: "RemainingCapacity"
        offset: 0
        len: 2
        is_signed: false
        factor: 1.0
        unit: "mAh"

diagnostics2:

  - id: 0x14
    fields:
      - name: "FETTemperature"
        offset: 0
        len: 2
        is_signed: true
        factor: 0.1
        unit: "°C"

      - name: "CellTemperature_1"
        offset: 2
        len: 2
        is_signed: true
        factor: 0.1
        unit: "°C"

      - name: "CellTemperature_2"
        offset: 4
        len: 2
        is_signed: true
        factor: 0.1
        unit: "°C"

  - id: 0x15
    fields:
      - name: "CellTemperature_3"
        offset: 0
        len: 2
        is_signed: true
        factor: 0.1
        unit: "°C"

      - name: "CellTemperature_4"
        offset: 2
        len: 2
        is_signed: true
        factor: 0.1
        unit: "°C"

      - name: "CellTemperature_5"
        offset: 4
        len: 2
        is_signed: true
        factor: 0.1
        unit: "°C"


topics: ["AccuCurrent", "RemainingCapacity", FETTemperature]

#topics:
#  actual_current: "AccuCurrent"
#  remaining_capacity: "RemainingCapacity"
