polls:
  - id: "0101"
    name: "AllStatusRegister"
    parameters:
      - field: "AkkuStatusRegister"
        len: 2
        signed: false
      - field: "AkkuStatusRegister_2"
        len: 2
        signed: false
      - field: "ProjectStatusRegister"
        len: 2
        signed: false
      - field: "SystemStatusRegister"
        len: 2
        signed: false

  - id: "0102"
    name: "AkkuCurrent"
    parameters:
      - field: "AkkuCurrent"
        len: 2
        signed: true

  - id: "0103"
    name: "AkkuPackVoltage"
    parameters:
      - field: "AkkuPackVoltage"
        len: 2
        signed: false

  - id: "0104"
    name: "AllTemperatures"
    parameters:
      - field: "FETTemperature"
        len: 2
        signed: true
      - field: "CellTemperature1"
        len: 2
        signed: true
      - field: "CellTemperature2"
        len: 2
        signed: true

  - id: "0105"
    name: "AllTemperatures2"
    parameters:
      - field: "CellTemperature3"
        len: 2
        signed: true
      - field: "CellTemperature4"
        len: 2
        signed: true
      - field: "CellTemperature5"
        len: 2
        signed: true

  - id: "0106"
    name: "AllCapacities"
    parameters:
      - field: "RemainingCapacity"
        len: 2
        signed: false
      - field: "FullChargeCapacity"
        len: 2
        signed: false
      - field: "DesignCapacity"
        len: 2
        signed: false


topics:
  actual_current:
    id: 0x102
    offset: 0
    len: 2
    signed: true
    factor: 0.01

  actual_voltage:
    id: 0x103
    offset: 0
    len: 2
    signed: false
    factor: 0.01

  remaining_capacity:
    id: 0x106
    offset: 0
    len: 2
    signed: false
    factor: 1
