## This file should be loaded under <robot description>_collision

default_collision_operations:
  - object1: platform
    object2: arm
    operation: enable
    
  - object1: torso
    object2: arm
    operation: enable
    
  - object1: tablet
    object2: arm
    operation: enable
    
  - object1: base_link
    object2: arm_0_link
    operation: disable    
    
  - object1: platform
    object2: hand
    operation: enable
    
  - object1: torso
    object2: hand
    operation: enable
    
  - object1: tablet
    object2: hand
    operation: enable    
    
  - object1: arm
    object2: hand
    operation: enable
    
  - object1: sdh_palm_link
    object2: arm_7_link
    operation: disable

  - object1: sdh_palm_link
    object2: arm_6_link
    operation: disable
  
  - object1: hand
    object2: arm_5_link
    operation: disable


#  - object1: robot_body
#    object2: arms
#    operation: enable

#  - object1: robot_body
#    object2: l_end_effector
#    operation: enable

#  - object1: robot_body
#    object2: r_end_effector
#    operation: enable

#  - object1: left_arm
#    object2: right_arm
#    operation: enable

#  - object1: l_end_effector
#    object2: right_arm
#    operation: enable

#  - object1: l_end_effector
#    object2: left_arm
#    operation: enable

#  - object1: r_end_effector
#    object2: left_arm
#    operation: enable

#  - object1: r_end_effector
#    object2: right_arm
#    operation: enable

#  - object1: l_end_effector
#    object2: r_end_effector
#    operation: enable

#  - object1: l_shoulder_pan_link
#    object2: r_shoulder_pan_link
#    operation: disable

#  - object1: r_shoulder_pan_link
#    object2: robot_body
#    operation: disable

#  - object1: r_shoulder_lift_link
#    object2: robot_body
#    operation: disable

#  - object1: r_upper_arm_roll_link
#    object2: torso_lift_link
#    operation: disable

#  - object1: r_upper_arm_link
#    object2: torso_lift_link
#    operation: disable

#  - object1: r_upper_arm_link
#    object2: r_elbow_flex_link
#    operation: disable

#  - object1: r_elbow_flex_link
#    object2: r_forearm_link
#    operation: disable

#  - object1: r_forearm_link
#    object2: r_end_effector
#    operation: disable

#  - object1: r_wrist_flex_link
#    object2: r_end_effector
#    operation: disable

#  - object1: r_wrist_roll_link
#    object2: r_end_effector
#    operation: disable

#  - object1: l_shoulder_pan_link
#    object2: robot_body
#    operation: disable

#  - object1: l_shoulder_lift_link
#    object2: robot_body
#    operation: disable

#  - object1: l_upper_arm_roll_link
#    object2: torso_lift_link
#    operation: disable

#  - object1: l_upper_arm_link
#    object2: torso_lift_link
#    operation: disable

#  - object1: l_upper_arm_link
#    object2: l_elbow_flex_link
#    operation: disable

#  - object1: l_elbow_flex_link
#    object2: l_forearm_link
#    operation: disable

#  - object1: l_forearm_link
#    object2: l_end_effector
#    operation: disable

#  - object1: l_wrist_flex_link
#    object2: l_end_effector
#    operation: disable

#  - object1: l_wrist_roll_link
#    object2: l_end_effector
#    operation: disable

#  - object1: r_shoulder_pan_link
#    object2: base_link
#    operation: disable

#  - object1: l_shoulder_pan_link
#    object2: base_link
#    operation: disable
