## This file should be loaded under <robot description>_planning

## the definition of each group
groups:

  - name: platform
    joints:
      base_joint
    links:
      base_link
      base_laser_front_link
      base_laser_rear_link
      base_laser_top_link      

  - name: torso
    joints:
      torso_lower_neck_pan_joint
      torso_lower_neck_tilt_joint
      torso_upper_neck_pan_joint
      torso_upper_neck_tilt_joint
    links:
      torso_lower_neck_tilt_link
      torso_upper_neck_tilt_link
      head_cover_link
      
  - name: tablet
    joints:
      torso_tray_joint
    links:
      torso_tray_link
      
  - name: arm
    joints:
      arm_1_joint
      arm_2_joint
      arm_3_joint
      arm_4_joint
      arm_5_joint
      arm_6_joint
      arm_7_joint
    links:
      arm_0_link
      arm_1_link
      arm_2_link
      arm_3_link
      arm_4_link
      arm_5_link
      arm_6_link
      arm_7_link


  - name: hand
    joints:
      sdh_finger_11_joint
      sdh_finger_12_joint
      sdh_finger_13_joint
      sdh_finger_21_joint
      sdh_finger_22_joint
      sdh_finger_23_joint
      sdh_thumb_2_joint
      sdh_thumb_3_joint
    links:
      sdh_palm_link
      sdh_finger_11_link
      sdh_finger_12_link
      sdh_finger_13_link
      sdh_finger_21_link
      sdh_finger_22_link
      sdh_finger_23_link
      sdh_thumb_1_link
      sdh_thumb_2_link
      sdh_thumb_3_link
      

  #this group is for the experimental cob_object_manipulation    
  - name: end_effector
    links: 
      sdh_palm_link
      sdh_finger_11_link
      sdh_finger_12_link
      sdh_finger_13_link
      sdh_finger_21_link
      sdh_finger_22_link
      sdh_finger_23_link
      sdh_thumb_1_link
      sdh_thumb_2_link
      sdh_thumb_3_link
