#all
lookat_joint_names: [lookat_lin_joint, lookat_x_joint, lookat_y_joint, lookat_z_joint]
chain_joint_names: [head_powerball_bottom_joint, head_powerball_side_joint]

# lookat_driver
update_rate: 68.0

# lookat controller parameters
base_link: head_powerball_base_link
tip_link: lookat_focus_frame
chain_vel_pub_topic: /torso_controller/command_vel
ptp_vel: 0.3

# frame_tracker
update_rate: 68.0
max_vel_lin: 0.6
max_vel_rot: 0.3

# trajectory controller parameters
joint_names: [lookat_lin_joint, lookat_x_joint, lookat_y_joint, lookat_z_joint]
ptp_vel: 1.0 # rad/sec
ptp_acc: 0.5 # rad/sec^2
max_error: 0.25 # rad
overlap_time: 0.4
frequency: 68
operation_mode: velocity

