//ROS typedefs
#include "ros/ros.h"

/* protected region user include files on begin */
/* protected region user include files end */

class safety_controller_config
{
public:

};

class safety_controller_data
{
// autogenerated: don't touch this class
public:
//input data
  
	
//output data
 

};

class safety_controller_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    safety_controller_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(safety_controller_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(safety_controller_data &data, safety_controller_config config)
    {
        /* protected region user update on begin */
		/* protected region user update end */
    }

    


    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
